---
title: "Completed randomized design"
author: "Hernandes Peres"
date: "`r Sys.Date()`"
output: html_document
---

### Data Loading
```{r}
data <- data.frame(
  rep = rep(1:5, each=4),
  variety = factor(rep(c("A", "B", "C", "D"), times=5)),
  yield = c(25, 31, 22, 33,
            26, 25, 26, 29,
            20, 28, 28, 31,
            23, 27, 25, 34,
            21, 24, 29, 28)
)
str(data)
```

### ANOVA Analysis
```{r}
fit <- aov(yield ~ variety, data = data)
anova(fit)
```

### Residual Analysis
```{r}
par(mfrow=c(2,2))
plot(fit)
layout(1)

residuals <- fit$residuals
mean_res <- mean(residuals)
sd_res <- sd(residuals)
cat("\n Sample mean =", mean_res, "\n Sample standard deviation =", sd_res, "\n")
```

### Normality Tests
```{r}
library(nortest)
qqnorm(residuals, col="blue", pch=20)
qqline(residuals, col="red", lwd=2)

t1 <- ks.test(residuals, "pnorm", mean_res, sd_res)
t2 <- lillie.test(residuals)
t3 <- cvm.test(residuals)
t4 <- shapiro.test(residuals)
t5 <- sf.test(residuals)
t6 <- ad.test(residuals)

tests <- c(t1$method, t2$method, t3$method, t4$method, t5$method, t6$method)
statistics <- c(t1$statistic, t2$statistic, t3$statistic, t4$statistic, t5$statistic, t6$statistic)
p_values <- c(t1$p.value, t2$p.value, t3$p.value, t4$p.value, t5$p.value, t6$p.value)
results <- data.frame(Test = tests, Statistic = statistics, P_Value = p_values)
print(results, digits=4)
```

### Homoscedasticity Tests
```{r}
plot(fitted(fit), resid(fit), col=4, pch=19, xlab="Fitted values", ylab="Residuals")
boxplot(residuals ~ data$variety, col=c(2,3,4,5), ylab="Residuals", xlab="Varieties")

library(lawstat)
levene.test(residuals, data$variety)
```

### Independence Check
```{r}
plot(fitted(fit), residuals, pch=19, col=4, xlab="Fitted Values", ylab="Residuals")
```

### Multiple Comparisons

```{r}
library(ExpDes.pt)
dic(data$variety, data$yield, quali = TRUE, mcomp = "lsdb", hvar= "bartlett", sigT = 0.05, sigF = 0.05)
```

# Completely randomized Design with unbalanced Data

```{r}
ls()
remove(list=ls(all=TRUE))
ls()
```

```{r}
data_unbalanced <- read.table("DataDesbalan.txt", head=TRUE)
str(data_unbalanced)
data_unbalanced$vend <- factor(data_unbalanced$vend)
str(data_unbalanced)
attach(data_unbalanced)

n <- length(data_unbalanced$result)
cat("\n n =", n, "\n")
```

```{r}
fit_unbalanced <- aov(result ~ vend, data = data_unbalanced)
anova(fit_unbalanced)
```

```{r}
residuals_unbalanced <- fit_unbalanced$residuals
mean_res_unbalanced <- mean(residuals_unbalanced)
sd_res_unbalanced <- sd(residuals_unbalanced)
cat("\n Sample mean =", mean_res_unbalanced, "\n Sample standard deviation =", sd_res_unbalanced, "\n")
```

```{r}
qqnorm(residuals_unbalanced, col="blue", pch=20)
qqline(residuals_unbalanced, col="red", lwd=2)
```

```{r}
library(nortest)
t1 <- ks.test(residuals_unbalanced, "pnorm", mean_res_unbalanced, sd_res_unbalanced)
t2 <- lillie.test(residuals_unbalanced)
t3 <- cvm.test(residuals_unbalanced)
t4 <- shapiro.test(residuals_unbalanced)
t5 <- sf.test(residuals_unbalanced)
t6 <- ad.test(residuals_unbalanced)
```

```{r}
tests <- c(t1$method, t2$method, t3$method, t4$method, t5$method, t6$method)
statistics <- c(t1$statistic, 
                t2$statistic, 
                t3$statistic, 
                t4$statistic, 
                t5$statistic, 
                t6$statistic)

p_values <- c(t1$p.value, t2$p.value, t3$p.value, t4$p.value, t5$p.value, t6$p.value)

results <- data.frame(Test = tests, Statistic = statistics, P_Value = p_values)

print(results, digits=4)
```

```{r}
fit_final <- aov(result ~ vend, data = data_unbalanced)
anova(fit_final)
```

```{r}
library(ExpDes.pt)
dic(data_unbalanced$vend, data_unbalanced$result, quali = TRUE, mcomp = "tukey", sigT = 0.05, sigF = 0.05)
```
